apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrypqr2110.azurecr.io/user-java:1.0 
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sqlconn  
