apiVersion: v1
kind: Secret
metadata:
  name: sqlconn
  namespace: default
type: Opaque
data:
  SQL_USER: c3FsYWRtaW5wUXIyMTEw  
  SQL_PASSWORD: eVY0cHQ0S2Ux 
  SQL_SERVER: c3Fsc2VydmVycHFyMjExMC5kYXRhYmFzZS53aW5kb3dzLm5ldA==  
  SQL_DBNAME: bXlkcml2aW5nREI= 
