apiVersion: apps/v1
kind: Deployment
metadata:
  name: helper
  labels:
    app: helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helper
  template:
    metadata:
      labels:
        app: helper
    spec:
      containers:
      - name: helper
        image: curlimages/curl  
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
