# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv4akst4-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 775ed698-70f3-46b1-b333-f32720a480e0   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kv4akst4                # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL-USER 
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_USER
        - |
          objectName: SQL-PASSWORD 
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQL-SERVER
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_SERVER
        - |
          objectName: SQL-DBNAME
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_DBNAME
    tenantId: /subscriptions/41aa2681-f55f-4834-9cc6-e6dc671b4ae5/resourceGroups/teamResources/providers/Microsoft.KeyVault/vaults/kv4akst4                  # The tenant ID of the key vault
